export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";
export const FETCHING_USER_PENDING = "FETCHING_USER_PENDING";
export const FETCHING_USER_SUCCESS = "FETCHING_USER_SUCCESS";
export const FETCHING_USER_FAILED = "FETCHING_USER_FAILED";
